# Generated by Django 4.1.3 on 2022-11-16 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('DEL_FL', models.BooleanField(default=False)),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syrup', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('bean', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffeebean', to='softdelete.bean')),
            ],
        ),
    ]
