# Generated by Django 4.1.3 on 2022-11-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True, verbose_name='get_bean_date')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='coffeebean',
            constraint=models.UniqueConstraint(fields=('origin', 'date'), name='origin-date composite key'),
        ),
    ]
